# Generated by Django 3.2.3 on 2021-08-26 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afianzado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Das',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_entrega', models.CharField(blank=True, max_length=128, null=True)),
                ('numero_atribuido', models.CharField(max_length=64)),
                ('fecha_embarque', models.DateField()),
                ('fecha_llegada', models.DateField()),
                ('documento_transporte', models.CharField(max_length=64)),
                ('tipo_carga', models.CharField(blank=True, max_length=64, null=True)),
                ('pais_procedncia', models.CharField(blank=True, max_length=255, null=True)),
                ('via_transporte', models.CharField(blank=True, max_length=64, null=True)),
                ('puerto_enbarque', models.CharField(blank=True, max_length=128, null=True)),
                ('ciudad_importador', models.CharField(blank=True, max_length=128, null=True)),
                ('empresa_tranporte', models.CharField(max_length=128, null=True)),
                ('identificacion_carga', models.CharField(blank=True, max_length=128, null=True)),
                ('monto_flete', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('total_items', models.IntegerField(blank=True, default=0, null=True)),
                ('peso_neto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9)),
                ('total_bultos', models.IntegerField(default=0)),
                ('unidades_comerciales', models.IntegerField(default=0)),
                ('total_tributos', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('valor_seguros', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('cif', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('peso_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('unidades_fisicas', models.IntegerField(default=0)),
                ('valor_fob', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Importacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=64)),
                ('tipo', models.CharField(blank=True, max_length=64)),
                ('origen', models.CharField(blank=True, max_length=64)),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mercancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('subpartida', models.CharField(max_length=128)),
                ('por_advalorem', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_woocommerce', models.IntegerField(blank=True, default=0)),
                ('sku', models.CharField(max_length=16, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('precio_compra', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('precio_neto', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('variacion', models.BooleanField(default=False)),
                ('parent_id', models.IntegerField(blank=True, default=0)),
                ('imagen', models.URLField(blank=True, default='')),
                ('categorias', models.CharField(blank=True, max_length=512, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('mercancia', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mercancia')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=64)),
                ('nombre', models.CharField(blank=True, max_length=64)),
                ('pais', models.CharField(blank=True, max_length=64)),
                ('telefono', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=16)),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('peso', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='Peso unitario (g)')),
                ('cantidad', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('proveedor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('das', models.IntegerField(default=0)),
                ('afianzado', models.IntegerField(default=0)),
                ('estado', models.IntegerField(default=0)),
                ('importacion', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.importacion')),
            ],
        ),
        migrations.CreateModel(
            name='Factura_proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cajas', models.IntegerField(default=1)),
                ('valor_factura', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('valor_envio', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('comision_envio', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('comision_tarjeta', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('isd', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('total_pago', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('extra', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('importacion', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.importacion')),
                ('proveedor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Factura_afianzado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero', models.CharField(blank=True, max_length=64)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('afianzado', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.afianzado')),
                ('importacion', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.importacion')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_importacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('novedades', models.CharField(blank=True, max_length=255)),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('subtotal2', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('peso', models.IntegerField(default=0)),
                ('advalorem2', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('fodinfa2', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('iva2', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('ps', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('pr', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('prt', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('costo1', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('costo2', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('costo3', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('inc_porcentual', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('inc_dolares', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('nuevo_costo', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('total_inventario', models.IntegerField(default=0)),
                ('actualizado', models.CharField(choices=[(1, 'SI'), (0, 'NO')], default=0, max_length=2)),
                ('das', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.das')),
                ('importacion', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.importacion')),
                ('mercancia', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mercancia')),
                ('producto', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('proveedor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_das',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advalorem1', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('fodinfa1', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('iva1', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('subtotal1', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('das', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.das')),
                ('mercancia', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mercancia')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_afianzado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('al_peso', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('al_precio', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('factura_afianzado', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.factura_afianzado')),
            ],
        ),
        migrations.AddField(
            model_name='das',
            name='importacion',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.importacion'),
        ),
    ]
