# Generated by Django 3.2.3 on 2021-06-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor_producto',
            old_name='ku',
            new_name='sku',
        ),
    ]
