# Generated by Django 3.2.3 on 2021-06-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_ku_proveedor_producto_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='das',
            name='pnumero_atribuido',
        ),
        migrations.AddField(
            model_name='das',
            name='numero_atribuido',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
