# Generated by Django 3.2.3 on 2021-06-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210609_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='das',
            name='ciuda_importador',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='das',
            name='empresa_tranportenumero_entrega',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='das',
            name='identificacion_carga',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='das',
            name='monto_flete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='das',
            name='numero_entrega',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='das',
            name='pais_procedncia',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='das',
            name='puerto_enbarque',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='das',
            name='tipo_carga',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='das',
            name='total_items',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='das',
            name='via_transporte',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
