# Generated by Django 3.2.3 on 2021-06-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210609_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='das',
            old_name='empresa_tranportenumero_entrega',
            new_name='empresa_tranporte',
        ),
    ]
