# Generated by Django 3.2.3 on 2021-06-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_empresa_tranportenumero_entrega_das_empresa_tranporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='das',
            name='documento_transporte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
