# Generated by Django 3.2.3 on 2021-06-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_das_documento_transporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='das',
            name='documento_transporte',
            field=models.CharField(max_length=64),
        ),
    ]
