# Generated by Django 3.2.3 on 2021-06-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_das_documento_transporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor_producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
