# Generated by Django 3.2.3 on 2021-06-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_proveedor_producto_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='mombre',
            new_name='nombre',
        ),
    ]
