# Generated by Django 3.2.3 on 2021-07-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_mombre_proveedor_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacion',
            name='fecha',
            field=models.DateField(help_text='Ejemplo: 2021-07-07'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_woocommerce',
            field=models.IntegerField(blank=True),
        ),
    ]
