# Generated by Django 3.2.3 on 2021-07-14 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210709_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='das',
            old_name='ciuda_importador',
            new_name='ciudad_importador',
        ),
    ]
