# Generated by Django 3.2.3 on 2021-07-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_ciuda_importador_das_ciudad_importador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura_afianzado',
            name='subtotal',
            field=models.DecimalField(decimal_places=4, max_digits=9),
        ),
    ]
