# Generated by Django 3.2.3 on 2021-07-20 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_factura_afianzado_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_importacion',
            name='mercancia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mercancia'),
        ),
        migrations.AddField(
            model_name='detalle_importacion',
            name='proveedor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.proveedor'),
        ),
    ]
