# Generated by Django 3.2.3 on 2021-07-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210719_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='das',
            name='pais_procedncia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
