# Generated by Django 3.2.3 on 2021-07-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210721_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_importacion',
            name='detalle_das',
        ),
        migrations.RemoveField(
            model_name='detalle_importacion',
            name='factura_proveedor',
        ),
    ]
