# Generated by Django 3.2.3 on 2021-07-23 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210723_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_importacion',
            name='das',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.das'),
        ),
    ]
