# Generated by Django 3.2.3 on 2021-07-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_detalle_importacion_das'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importacion', models.IntegerField(default=0)),
                ('das', models.IntegerField(default=0)),
                ('afianzado', models.IntegerField(default=0)),
                ('estado', models.IntegerField(default=0)),
            ],
        ),
    ]
