# Generated by Django 3.2.3 on 2021-07-30 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='importacion',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.importacion'),
        ),
    ]
