# Generated by Django 3.2.3 on 2021-08-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_historial_importacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
