# Generated by Django 3.2.3 on 2021-08-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210803_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_importacion',
            name='actualizado',
            field=models.CharField(choices=[('1', 'SI'), ('0', 'NO')], default='NO', max_length=2),
        ),
    ]
