# Generated by Django 3.2.3 on 2021-08-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_detalle_importacion_actualizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_importacion',
            name='actualizado',
            field=models.CharField(choices=[(1, 'SI'), (0, 'NO')], default=0, max_length=2),
        ),
    ]
