# Generated by Django 3.2.3 on 2021-08-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210812_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_woocommerce',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
