# Generated by Django 3.2.3 on 2021-08-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_producto_id_woocommerce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categorias',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
