# Generated by Django 3.2.3 on 2021-08-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210817_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_importacion',
            name='peso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='factura_afianzado',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
